name: TextWhitelist
version: 3.0-beta
main: io.github.cowboyoriginal.textwhitelist.TextWhitelist
author: Cowboy-original
description: A powerful text-file based whitelist with multiple modes and full in-game management.
commands:
  whitelistxt:
    description: Main command for the TextWhitelist plugin.
    aliases: [wltxt]
    permission: textwhitelist.admin
    permission-message: You do not have permission to use this command.
    usage: |
      §eTextWhitelist Commands:
      §a/wltxt help §7- Shows a detailed help message.
      §a/wltxt list [players|admins|all] [page] §7- Lists players on the whitelist.
      §a/wltxt change <players|admins> §7- Changes the active whitelist mode.
      §a/wltxt add <player|admin> <name> §7- Adds a player to a list.
      §a/wltxt remove <player|admin> <name> §7- Removes a player from a list.
      §a/wltxt <enable|disable> §7- Enables or disables the whitelist plugin.